pragma solidity ^0.6.0;

contract ProposalType {
    enum ProposalType {
        COMMON,
        CHANGING_MAIN_GOVERNANACE_MIN_QUORUM,
        CHANGING_GOVERNOR,
        CHANGING_FUND_GOVERNANACE_QUORUM,
        CHANGING_PERCENT_PER_WITHDRAWAL,
        CHANGING_MAXIMUM_PERCENT_PER_WITHDRAWAL,
        CHANGING_MAIN_GOVERNANACE_MIN_AMOUNT_TO_PROPOSE
    }
}